debian/kadu.desktop usr/share/applications
debian/kadu.xpm /usr/share/pixmaps
debian/tmp/usr/bin/kadu
debian/tmp/usr/bin/kadu-mozilla
debian/tmp/usr/lib/kadu/modules/account_management.so
debian/tmp/usr/lib/kadu/modules/advanced_userlist.so
debian/tmp/usr/lib/kadu/modules/alsa_sound.so
debian/tmp/usr/lib/kadu/modules/arts_sound.so
debian/tmp/usr/lib/kadu/modules/autoaway.so
debian/tmp/usr/lib/kadu/modules/autoresponder.so
debian/tmp/usr/lib/kadu/modules/bin/arts_sound
debian/tmp/usr/lib/kadu/modules/config_wizard.so
debian/tmp/usr/lib/kadu/modules/dcc.so
debian/tmp/usr/lib/kadu/modules/default_sms.so
debian/tmp/usr/lib/kadu/modules/desktop_docking.so
debian/tmp/usr/lib/kadu/modules/dsp_sound.so
debian/tmp/usr/lib/kadu/modules/esd_sound.so
debian/tmp/usr/lib/kadu/modules/exec_notify.so
debian/tmp/usr/lib/kadu/modules/ext_sound.so
debian/tmp/usr/lib/kadu/modules/hints.so
debian/tmp/usr/lib/kadu/modules/history.so
debian/tmp/usr/lib/kadu/modules/migration.so
debian/tmp/usr/lib/kadu/modules/nas_sound.so
debian/tmp/usr/lib/kadu/modules/sms.so
debian/tmp/usr/lib/kadu/modules/speech.so
debian/tmp/usr/lib/kadu/modules/voice.so
debian/tmp/usr/lib/kadu/modules/window_notify.so
debian/tmp/usr/lib/kadu/modules/wmaker_docking.so
debian/tmp/usr/lib/kadu/modules/x11_docking.so

