#!/bin/bash

$QTDIR/bin/lupdate -noobsolete -verbose ../*.cpp ../*/*.cpp ../*/*/*.cpp ../gui/import_history.ui -ts import_history_it.ts
$QTDIR/bin/lupdate -noobsolete -verbose ../*.cpp ../*/*.cpp ../*/*/*.cpp ../gui/import_history.ui -ts import_history_pl.ts
$QTDIR/bin/lupdate -noobsolete -verbose ../*.cpp ../*/*.cpp ../*/*/*.cpp ../gui/import_history.ui -ts import_history_de.ts
$QTDIR/bin/lupdate -noobsolete -verbose ../*.cpp ../*/*.cpp ../*/*/*.cpp ../gui/import_history.ui -ts import_history_fr.ts
