.TH KADU 1
.SH NAME
kadu-mozilla \- a helper script to open URL's shown in the chat window
.SH SYNOPSIS
.B kadu-mozilla
\fIURL\fP
.SH DESCRIPTION
\fIkadu-mozilla\fP is a helper script used by \fIkadu\fP to open \fIURL\fP
links in an external (\fImozilla/firefox\fP) browser. The link is opened in a
new tab.
.SH SEE ALSO
.BR kadu (1)
.SH AUTHOR
kadu was written by Kadu Team (see /usr/share/kadu/doc/AUTHORS file for details).
.PP
This manual page was written by Patryk Cisek <patryk@prezu.one.pl>,
for the Debian project (but may be used by others).
